# This is a basic workflow to help you get started with Actions

name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@0.1.4
        with:
          find: "127.0.0.1:5500/"
          replace: "vakareo.github.io/learning-maths/"
